### ISSUE TITLE
support for PDF::Builder?

### ISSUE THREAD

**Issue by jhannah** [jhannah/pdf-textblock#6]
Originally: https://rt.cpan.org/Ticket/Display.html?id=133974
PMPERRY@cpan.org wrote:

I'm trying to modify the package CtrlO::PDF, which calls PDF::TextBlock, to be able to use either PDF::API2, or PDF::Builder. I see that PDF::TextBlock seems to have one hard dependency on PDF::API2 at line 239:
```
   unless (ref $pdf eq "PDF::API2") {
      croak "pdf attribute (a PDF::API2 object) required";
   }
```
change to
```
   unless (ref $pdf eq "PDF::API2" ||
           ref $pdf eq "PDF::Builder") {
      croak "pdf attribute (a PDF::API2 or PDF::Builder object) required";
   }
```
There are some other comments and POD around that would need to be updated too. Would you be interested in also supporting PDF::Builder (a follow-on to PDF::API2)?

**Comment by jhannah** [comment]
Yup. Happy to apply this patch. Unless you want to submit a PR so you get credit in git / github?

**Comment by PhilterPaper** [comment]
I already get enough blame on GitHub ;-). Be sure to hit the various places in the POD and comments that mention only PDF::API2, if you would. Appreciate it, and looking forward to the next release!

**Comment by jhannah** [comment]
@PhilterPaper I haven't actually used this module for anything in many years. I'm happy to make the 1-liner code change you asked for, but it would take hours for me to write tests (proving) and documentation (demonstrating) that `PDF::Builder` works just as well. That's more work than I'm willing to throw at this. I'm willing to throw a sentence into the docs "anywhere you see `PDF::API2` you can substitute `PDF::Builder` if you want."

But I'm not sure what to do about the [Makefile.PL requirement](https://github.com/jhannah/pdf-textblock/blob/master/Makefile.PL#L13). It currently contains a requirement of `PDF::API2`. Do you know how I would say "require X or Y"?
The tests, as currently written, require `PDF::API2`. So... I guess the module needs to require that one regardless so installers are happy?

**Comment by jhannah** [comment]
The tests, as currently written, require `PDF::API2`. So... I guess the module needs to require that one regardless so installers are happy?

**Comment by jhannah** [comment]
Suggestions from Perl Foundation Slack:
Matthew Horsfall  13:13
I think in your makefile you could try to load both and require the one that’s found in order of preference
Failing that, pick one as default
And if the tests need a specific one put that in the test requires or build requires

Dan Book  13:42
yes, your Makefile.PL could dynamically add one or the other to PREREQ_PM depending what is available
and TEST_REQUIRES what your tests need, or make your tests also able to use either
or make different test files, and use Test::Needs to determine whether the module it needs is available
also note that TEST_REQUIRES is in addition to PREREQ_PM for what tests need, so if you dynamically require one or the other for runtime deps it will also ensure one of them is available for tests

**Comment by PhilterPaper** [comment]
I don't know if there's any way to specify prereq 'X or Y'. CtrlO::PDF is going to face the same issue. It can check to see which one is installed (in some desired order), and use the first one it finds. It will still fail and die if neither is found. I haven't looked at Dan Book's suggestion about Test::Needs and TEST_REQUIRES, but if it can end up installing one or the other so that installation testing can proceed, that would do the job. Both PDF::API2 and PDF::Builder can be installed without interfering with each other, but I'm sure users would prefer to have just one automatically installed (and not install the alternate if one is already there). It certainly should be possible in the Makefile.PL (per Matthew Horsfall) to check if either one is already there, and prereq one if neither is installed.

What someone long ago did with PDF::Table was to create a "Mock" PDF::API2 library to use in t-tests. All it is are some dummy stubs for PDF::API2 (or PDF::Builder) routines called during installation test. They don't actually do anything useful. This allows PDF::Table to be installed even if PDF::API2 was missing (ditto for PDF::Builder), while the t-tests are still being hard coded to use PDF::API2.

**Comment by PhilterPaper** [comment]
How about the following (assuming I can do all of it): 

1. Makefile.PL removed fixed PDF::API2 prereq. Check if either PDF::Builder or PDF::API2 is already installed. If **neither** is, add one to the PREREQ list (I would prefer it to be PDF::Builder for obvious reasons, but if you're happy with PDF::API2, that could be the default prereq).
2. If you're anxious about testing for the specific package, set up t-tests to handle the one (or both) that are installed, skipping the missing package. For example, t/20-demo.t skips if PDF::API2 _not_ installed, and new t/21-demo.t is 20 modified to use PDF::Builder instead, and skip if PDF::Builder is not installed.
3. TextBlock.pm itself modified per my earlier comments to happily work with either PDF::API2 or PDF::Builder. Ditto for Font.pm.

Would that do the job for you? Do you require a PR rather than just instructions? I just don't want to go through setting up a repository fork if you're not going to accept the resulting PR.

I'll leave it to you to modify Makefile.PL to add a bugtracker entry to GitHub (RT is closing down), unless you want me to do that too.

**Comment by jhannah** [comment]
@PhilterPaper if the tests still pass (including human eyeballing of the generated PDF files to ensure the world didn't explode lol) all your PR(s) would be happily merged and pushed to PAUSE. I'm granting you write to this github repo, and I can grant you CO-MAINT in PAUSE if you want it. :)

**Comment by jhannah** [comment]
@PhilterPaper I pushed 58ba3bc which might fix the linking to RT. RT is no longer mentioned anywhere in the repository.

**Comment by PhilterPaper** [comment]
I made a PR with the necessary changes. It awaits your inspection and pull/merge.

**Comment by jhannah** [comment]
Ooo awesome thanks!!

Fascinating, I've never seen this bug before, presumably it's caused by random text block output, has nothing to do with your changes. :)

<img width="773" alt="Screen Shot 2021-01-08 at 11 14 38 AM" src="https://user-images.githubusercontent.com/62206/104044561-15ab5080-51a3-11eb-9c71-946981cf4228.png">

**Comment by jhannah** [comment]
v0.12 pushed to PAUSE. Thanks!!

**Comment by PhilterPaper** [comment]
You might want to twitch the code to just left-justify the _last_ line in the paragraph, rather than trying to stretch it out to full width. My guess is that it has something to do with what you're seeing. I have no idea why the "tags" were not stripped out from that line.
